# Generated by Django 5.2.5 on 2025-10-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                (
                    "price_tier_1",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço (Faixa 1)"
                    ),
                ),
                (
                    "price_tier_2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço (Faixa 2)",
                    ),
                ),
                (
                    "price_tier_3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço (Faixa 3)",
                    ),
                ),
                (
                    "quantity_limit_1",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Limite opcional para a primeira faixa de desconto",
                        null=True,
                        verbose_name="Limite de quantidade para Faixa 1",
                    ),
                ),
                (
                    "quantity_limit_2",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Limite opcional para a segunda faixa de desconto",
                        null=True,
                        verbose_name="Limite de quantidade para Faixa 2",
                    ),
                ),
                (
                    "quantity_limit_3",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Limite opcional para a terceira faixa de desconto",
                        null=True,
                        verbose_name="Limite de quantidade para Faixa 3",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
