# Generated by Django 5.2.5 on 2025-10-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="quantity_limit_3",
        ),
    ]
