# Generated by Django 5.2.5 on 2025-10-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_product_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="products/product_default.png", upload_to="products/"
            ),
        ),
    ]
