# Generated by Django 5.2.5 on 2025-10-28 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nome do Método de Pagamento",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cash", "Dinheiro"),
                            ("pix", "PIX"),
                            ("debit", "Cartão de Débito"),
                            ("credit", "Cartão de Crédito"),
                            ("boleto", "Boleto"),
                            ("other", "Outro"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Tipo de Pagamento",
                    ),
                ),
                (
                    "internal_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Taxa cobrada pela operadora (afeta o lucro da loja).",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Taxa Interna (%)",
                    ),
                ),
                (
                    "min_installment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Mínimo para Parcelar (R$)",
                    ),
                ),
                (
                    "max_installments",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        null=True,
                        verbose_name="Máximo de Parcelas",
                    ),
                ),
                (
                    "no_interest_installments",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        null=True,
                        verbose_name="Parcelas Sem Juros",
                    ),
                ),
                (
                    "customer_interest_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Juros ao Cliente (%) ao mês",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Método de Pagamento",
                "verbose_name_plural": "Métodos de Pagamento",
                "ordering": ["name"],
            },
        ),
    ]
