# Generated by Django 5.2.5 on 2025-11-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="cnpj_or_cpf",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="CNPJ or CPF"
            ),
        ),
    ]
